  
database:
  
  version: '2'
  
  database_load: mysql
  database_save: mysql
  
  sql:
    hostname: mysql.shockbyte.hil2.shockbyte.host
    port: '3306'
    dbname: 75eedc3b19-rootmc
    table_prefix: towny_
    username: 75eedc3b19-rootmc-admin
    password: ''  # Shockbyte panel password — set on live host only
    flags: ?verifyServerCertificate=false&useSSL=false&useUnicode=true&characterEncoding=utf-8
  
    disable_backup_warning: 'false'
  
    pooling:
      max_pool_size: '5'
      max_lifetime: '180000'
      connection_timeout: '5000'
