package com.rootrecord.blocknotes.ui.navigation

object BlockNotesNavRoutes {
    const val NOTES = "notes"
    const val NOTEBOOK = "notebook/{notebookId}"
    const val NOTE_EDITOR = "note/{noteId}"
    const val NOTE_NEW = "note/new/{notebookId}"
    const val WAYPOINTS = "waypoints"
    /** @deprecated use [WAYPOINTS]; kept for deep links */
    const val COORDS = "coords"
    const val WAYPOINT_ADD = "waypoint/add"
    const val COORD_ADD = "coord/add"
    const val WAYPOINT_DETAIL = "waypoint/{waypointId}"
    const val COORD_DETAIL = "coord/{coordId}"
    const val AREA_DETAIL = "area/{areaId}"
    const val REFERENCE = "reference"
    const val REF_CATEGORY = "reference/{category}"
    const val WORLDS = "worlds"
    const val SERVER = "server"
    const val SERVER_DETAIL = "server/{serverId}"
    const val WORLD_DETAIL = "world/{worldId}"
    const val WORLD_MAP = "world/{worldId}/map"
    const val WORLD_AI_REPORT = "world/{worldId}/ai-report"
    const val REALM = "realm"
    const val REALM_GROUP = "realm/group/{groupId}/{groupName}"
    const val MORE = "more"
    const val SETTINGS = "settings"
    const val FEEDBACK = "feedback"
    const val AUTH = "auth"
    const val SEARCH = "search"
    const val GALLERY = "gallery"
    const val TRASH = "trash"
    const val TEMPLATES = "templates"
    const val BUILD_PLANNER = "build_planner"
    const val TIMELINE = "timeline"

    fun notebook(notebookId: Long) = "notebook/$notebookId"
    fun note(noteId: Long) = "note/$noteId"
    fun newNote(notebookId: Long) = "note/new/$notebookId"
    fun waypoint(waypointId: Long) = "waypoint/$waypointId"
    fun coord(coordId: Long) = "coord/$coordId"
    fun area(areaId: Long) = "area/$areaId"
    fun referenceCategory(category: String) = "reference/$category"
    fun world(worldId: Long) = "world/$worldId"
    fun worldMap(worldId: Long) = "world/$worldId/map"
    fun worldAiReport(worldId: Long) = "world/$worldId/ai-report"
    fun serverDetail(serverId: String) = "server/$serverId"
    fun realmGroup(groupId: String, groupName: String) =
        "realm/group/$groupId/${groupName.replace("/", "_")}"
}
